name: Workflow
on:
  # push:
  pull_request:
    types:  ["closed","opened","assigned","reopened"]
  schedule:
    - cron: "0/5 * * * * "



jobs:
  runs-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: action workflow example
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Satyam Kumar
      - name: print time of message print
        run: echo "${{steps.greet.outputs.time}}"
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout to updated commit
        uses: actions/checkout@v1
      - name: List Files after Checkout
        run: |
          pwd
          ls -a
      - name: Global Variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"
            
