name: XXX Workflow
on: [push]


jobs:
  runs-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: action workflow example
        id: actions
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Satyam
      - name: print time of message print
        run: echo "${{steps.actions.output.time}}""