name: Testing Workflow Logic
on: [push]

jobs:
  runs-linux-commads:
    runs-on: ubuntu-latest
    needs: ["runs-windows-command"]
    steps:
      - name: Echo a String Message
        run: |
          echo "Echoing String Message"
          git --version

  runs-windows-command:
    runs-on: windows-latest
    steps:
      - name: Get Location
        run: Get-Location
      - name: Run command on Bash shell in windows-latest
        run: pwd
        shell: bash

  